/* Modelagem Básica - 

ENTIDADE = TABELA
CAMPOS = ATRIBUTOS
ARRUMAÇÃO DOS CAMPOS NO BR MODELO - CLICAR NA ESTIDADE E CTRL+O*/

CLIENTE

NOME - CARACTERES (30)
CPF - NUMÉRICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDEREÇO - CARACTER (100)
SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS*/

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM 

/*FASE 03 - DBA / AD */ 

MODELAGEM FÍSICA - SCRIPTS DE BANCO 

/* INICIANDO A MODELAGEM FISICA */ 

/* CRIANDO O BANCO DE DADOS */ 

CREATE DATABASE PROJETO;

CREATE DATABASE EXEMPLO;

/* CONECTANDO-SE AO BANCO */ 

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */ 

CREATE TABLE CLIENTE(
NOME VARCHAR(30),
SEXO CHAR(1),
EMAIL VARCHAR(30),
CPF INT(11),
TELEFONE VARCHAR(30),
ENDEREÇO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;


/* SINTAXE BÁSICA DE INSERÇÃO - INSERT INTO [TABELA]... */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES ('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110','MAIA LACERDA ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE', 'M', 'NULL', 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');



/* FORMA 02 - COLOCANDO AS COLUNAS */ 

INSERT INTO CLIENTE(NOME, SEXO, ENDEREÇO, TELEFONE, CPF) VALUES('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856); 




/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */ 

INSERT INTO CLIENTE VALUES('ANA','F', 'ANAGLOBO@GMAIL.COM', 85548962, '548556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
('CARLA', 'F', 'CARLA@GMAIL.COM.BR', 7745828, '66587456', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG'); 


/* O COMANDO SELECT 
selecao projecao e juncao 
*/

SELECT NOW();

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'LEONARDO' AS ALUNO;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';


/* ALIAS DE COLUNAS */

SELECT NOME, SEXO , EMAIL FROM CLIENTE; 

SELECT NOME AS CLIENTE, SEXO , EMAIL FROM CLIENTE; 

SELECT NOME, SEXO, EMAIL, ENDEREÇO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDEREÇO, NOME FROM CLIENTE; 

SELECT EMAIL, SEXO, ENDEREÇO, NOME, NOW() AS DATA_HORA FROM CLIENTE; 

SELECT EMAIL, SEXO, ENDEREÇO, NOME AS CLIENTE, NOW() AS DATA_HORA FROM CLIENTE; 



/* APENAS PARA FINS ACADEMICOS */ 

SELECT * FROM CLIENTE; 



/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE; 

/* FILTRANDO */ 

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M'; 


SELECT NOME, ENDEREÇO FROM CLIENTE
WHERE SEXO = 'F'; 


SELECT NOME, SEXO FROM CLIENTE
WHERE ENDEREÇO = 'RJ'; 

/* UTILIZANDO O LIKE */


SELECT NOME, SEXO FROM CLIENTE
WHERE ENDEREÇO LIKE 'RJ'; 


/* CARACTER CORINGA % -> QUALQUER COISA*/


SELECT NOME, SEXO FROM CLIENTE
WHERE ENDEREÇO LIKE '%RJ'; 


SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE '%RJ'; 


SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE '%CENTRO%';

/* OPERADORES LOGICOS
OR -> PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA PELO MENOS UMA CONDIÇÃO DEVE SER VERDADEIRA 
AND -> PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA TODAS AS CONDIÇÕES DEVEM SER VERDADEIRAS */

/* OR - OU */ 

USE PROJETO; 

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE
SEXO = 'M' OR ENDERECO LIKE '%RJ'; 

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'F' OR ENDERECO LIKE '%ESTACIO'; 

/* AND - E */ 

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' AND ENDERECO LIKE '%RJ'; 

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */ 

SELECT COUNT(*) FROM CLIENTE; 

SELECT COUNT(*)
FROM CLIENTE; 

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*)
FROM CLIENTE 
GROUP BY SEXO; 

/* PERFORMANCE EM OPERADORES LOGICOS */

/* 1 MILHAO DE REGISTROS 

PARA CONTAR
SELECT COUNT(*) FROM CLIENTE; 

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO; 

SELECT CIDADE, COUNT(*) FROM CLIENTE 
GROUP BY CIDADE;

CONDICAO
SEXO = F
CIDADE = RIO DE JANEIRO

SITUACAO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE 
WHERE SEXO = 'F'
OR CIDADE = 'RIO DE JANEIRO';

SITUACAO - TRATANDO COM E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE 
WHERE CIDADE = 'RIO DE JANEIRO'
AND SEXO = 'F'; */ 

/* FILTRANDO VALORES NULOS */

SELECT NOME, SEXO, ENDEREÇO
FROM CLIENTE 
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDEREÇO
FROM CLIENTE 
WHERE EMAIL IS NOT NULL;

/* IS OU NOT NULL */ 

/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */ 

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT NOME, EMAIL
FROM CLIENTE;

/* WHERE - VAI SER O SEU MELHOR AMIGO DA VIDA PRA VIDA INTEIRA */

SELECT * FROM CLIENTE
WHERE NOME = 'LILIAN'; 

UPDATE CLIENTE
SET EMAIL = 'JOAO@IG.COM.BR'
WHERE NOME = 'JOAO';

/* COMMIT E ROLLBACK */ 

DELETE FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE;

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE;

SELECT 6 - 1; 

SELECT * FROM CLIENTE; 

SELECT * FROM  CLIENTE -- OR TRAZ TODO MUNDO COM PELO MENOS UMA DAS DUAS CONDIÇÕES
WHERE NOME = 'CARLA';
OR EMAIL = 'LILIAN@HOTMAIL.COM';

DELETE FROM CLIENTE -- TRAZ APENAS O REGISTRO QUE SATISFAÇA AS DUAS CONDIÇOES
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT * FROM CLIENTE;

/* ENTRANDO COM MAIS TELEFONES */ 

SELECT * FROM CLIENTE;

UPDATE CLIENTE
SET TELEFONE = '22923110 - 97865434'
WHERE NOME = 'JOAO';

SELECT * FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE
GROUP BY SEXO;

/* PRIMEIRA FORMA NORMAL */ 

/*

1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA PLANILHA

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA QUANDO O CAMPO
FOR DIVISÍVEL

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE 
IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO.
ISSO É O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY

*/
